# Generated by Django 2.0.2 on 2018-02-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0003_auto_20180227_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Rel. Entregue',
                'verbose_name_plural': 'Rel. Entregues',
            },
        ),
        migrations.AlterModelOptions(
            name='relatorioestagiario',
            options={'verbose_name': 'Relatório de estagiário', 'verbose_name_plural': 'Relatórios de estagiários'},
        ),
        migrations.AddField(
            model_name='relatorioestagiario',
            name='frequencia',
            field=models.CharField(choices=[('Satisfatória', 'Satisfatória'), ('Pendente', 'Pendente'), ('Insatisfatória', 'Insatisfatória')], default=0, max_length=50, verbose_name='Frequência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorioestagiario',
            name='entregue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='organizacional.Entregue', verbose_name='Rel. Entregue'),
            preserve_default=False,
        ),
    ]
