# Generated by Django 2.0.2 on 2018-03-06 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_estagiario_sexo'),
        ('organizacional', '0004_auto_20180227_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('periodo_declaracao', models.CharField(max_length=10, verbose_name='Periodo da Declaração')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Estagiario', verbose_name='Estagiario')),
            ],
            options={
                'verbose_name': 'Declaração de Matricula',
                'verbose_name_plural': 'Declarações de Matricula',
            },
        ),
        migrations.CreateModel(
            name='SuspensaoVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=100, unique=True, verbose_name='Nº Processo')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('termino', models.DateField(verbose_name='Termino')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Estagiario', verbose_name='Estagiario')),
            ],
            options={
                'verbose_name': 'Suspensão de vinculo',
                'verbose_name_plural': 'Suspensões de vinculos',
            },
        ),
    ]
