# Generated by Django 2.0.2 on 2018-03-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0005_declaracaomatricula_suspensaovinculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_vigencia', models.DateField(verbose_name='Início da Vigencia')),
                ('termino_vigencia', models.DateField(verbose_name='Termino da Vigencia')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacional.Cidade', verbose_name='Cidade')),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacional.Faculdade', verbose_name='Faculdade')),
            ],
            options={
                'verbose_name_plural': 'Convenios Com Intituições de Ensino',
                'verbose_name': 'Convenio Com Instituição de Ensino',
            },
        ),
    ]
