# Generated by Django 2.0.2 on 2018-05-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_estagiario_sexo'),
        ('organizacional', '0007_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('defensor_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defensor_anterior', to='pessoal.Defensor', verbose_name='Defensor anterior')),
                ('defensor_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defensor_novo', to='pessoal.Defensor', verbose_name='Defensor novo')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.Estagiario', verbose_name='Estagiário')),
                ('vara_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vara_anterior', to='organizacional.Vara', verbose_name='Vara anterior')),
                ('vara_nova', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vara_nova', to='organizacional.Vara', verbose_name='Vara nova')),
            ],
            options={
                'verbose_name': 'Histórico de Movimentação',
                'verbose_name_plural': 'Histórico de Movimentações',
            },
        ),
    ]
